### ISSUE TITLE
ｅｌｆ　ｒｕｎｅｓ　ｄｏｎ＇ｔ　ｗｏｒｋ

### ISSUE THREAD

**Issue by nortti** [lex/aesthetic#1]
Steps to reproduce:
input:whën
expected outcome: ｗｈëｎ OR ｗｈｅｎ
actual outcome: ｗｈￋｎ

Please fix ASAP

**Comment by lex** [comment]
ｙｅｓ　ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｒｅｐｏｒｔｉｎｇ．

ｗｉｌｌ　ｆｉｘ　ａｓａｐ

**Comment by lex** [comment]
Ｈｅｌｌｏ　ｎｏｒｔｔｉ，

Ｉ　ａｍ　ｖｅｒｙ　ｅｘｃｉｔｅｄ　ｔｏ　ｉｎｆｏｒｍ　ｙｏｕ　ｔｈａｔ　ｙｏｕｒ　ｉｓｓｕｅ　ｈａｓ　ｎｏｗ　ｂｅｅｎ　ｆｉｘｅｄ　ｉｎ　ｃｏｍｍｉｔ　https://github.com/lex/aesthetic/commit/1dcd2612ed5f29e8db25b134918ae43c476afa44．

Ｈｏｗｅｖｅｒ，　ｗｅ　ｄｉｓｃｏｖｅｒｅｄ　ａ　ｎｅｗ　ｂｕｇ　ｗｈｉｌｅ　ｗｒｉｔｉｎｇ　ｔｈｉｓ　ｍｅｓｓａｇｅ：　ｎｅｗｌｉｎｅｓ　ｄｏｎ＇ｔ　ｗｏｒｋ　ａｎｙｍｏｒｅ．

Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｙｏｕｒ　ｐａｔｉｅｎｃｅ．　Ｉ＇ｍ　ｖｅｒｙ　ｓｏｒｒｙ　ｆｏｒ　ａｎｙ　ｉｎｃｏｎｖｅｎｉｅｎｃｅ　ｙｏｕ　ｍｉｇｈｔ　ｅｘｐｅｒｉｅｎｃｅ　ｕｎｔｉｌ　ｉｔ　ｈａｓ　ｂｅｅｎ　ｆｉｘｅｄ．　Ｏｕｒ　ｔｅａｍ　ｉｓ　ｗｏｒｋｉｎｇ　ｖｅｒｙ　ｈａｒｄ　ｔｏ　ｆｉｘ　ｔｈｉｓ　ｉｓｓｕｅ．

**Comment by lex** [comment]
Ｉｎ　ｃａｓｅ　ｓｏｍｅｏｎｅ　ｗａｎｔｓ　ｔｏ　ｈｅｌｐ　ｗｉｔｈ　ｔｈｉｓ，　ｔｈｅｒｅ　ｉｓ　ａｎ　ｉｓｓｕｅ　ｗｉｔｈ　ｍｏｒｅ　ｄｅｔａｉｌｓ：　#2
