### ISSUE TITLE
ｎｅｗｌｉｎｅｓ　ｄｏｎｔ　ｗｏｒｋ

### ISSUE THREAD

**Issue by lex** [lex/aesthetic#2]
Steps to reproduce:
input: \n
expected outcome: an actual newline
actual outcome: nothing

**Comment by nortti** [comment]
ｙｅｓ ｉｔ＇ｓ ｆｕｃｋｅｄ

**Comment by lex** [comment]
Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｈｅｌｐ．
