### ISSUE TITLE
Ｐｌａｃｅｈｏｌｄｅｒ　ｔｅｘｔ　ｃｏｌｏｕｒ　ｕｎｆｉｔｔｉｎｇ　ｆｏｒ　ｂａｃｋｇｒｏｕｎｄ

### ISSUE THREAD

**Issue by nortti** [lex/aesthetic#4]
Steps to reproduce:
input:
expected outcome: legible placeholder texts
actual outcome: illegible placeholder texts

![Ｓｃｒｅｅｎｓｈｏｔ ｏｆ ｔｈｅ ｐｒｏｂｌｅｍ](https://screenshotscdn.firefoxusercontent.com/images/9a2d6091-9a12-4ead-a2d1-f46b7d771829.png)

Ｂｒｏｗｓｅｒ ｕｓｅｄ： ｆｉｒｅｆｏｘ

Ｉ ｌｏｏｋ ｆｏｒｗａｒｄ ｔｏ ｓｅｅｉｎｇ ｒｅａｄｉｎｇ ｔｈｅｓｅ ｔｅｘｔｓ ａｇａｉｎ ｏｎｃｅ ｉｔ＇ｓ ｆｉｘｅｄ．

Ｔｈａｎｋ ｙｏｕ．

**Comment by lex** [comment]
Ｈｉ　ｎｏｒｔｔｉ

Ｆｏｒ　ｍｅ　ｉｔ　ｌｏｏｋ　ｌｉｋｅ　ｔｈｉｓ　ｗｉｔｈ　Ｓａｆａｒｉ　１１．０．２：

<img width="581" alt="screenshot 2018-03-02 11 31 13" src="https://user-images.githubusercontent.com/5781244/36892530-b41271da-1e0d-11e8-9eda-6926a9a356fb.png">

Ｗｈａｔ　ｃｏｌｏｒ　ｗｏｕｌｄ　ｙｏｕ　ｓｕｇｇｅｓｔ？

**Comment by nortti** [comment]
Ｙｅｓ　ｉｔ　ａｐｐｅａｒｓ　ｔｈａｔ　ｆｉｒｅｆｏｘ＇ｓ　ｄｅｆａｕｌｔ　ｐｌａｃｅｈｏｌｄｅｒ　ｃｏｌｏｕｒ　ｉｓ　not great．　Ｓａｆａｒｉ　ｌｏｏｋｓ　ｇｏｏｄ．　Ｍａｙｂｅ　ｃｈａｎｇｅ　ｉｔ　ｔｏ　ｍａｔｃｈ　Ｃｈｒｏｍｅ，　ｆｏｒ　ｅｘａｍｐｌｅ？

Ｓｅｅ https://stackoverflow.com/a/41900282

**Comment by lex** [comment]
Ｈｅｌｌｏ　ｎｏｒｔｔｉ

Ｗｅ　ｔｗｅａｋｅｄ　ｔｈｅ　ｃｏｌｏｒｓ　ａ　ｂｉｔ．　Ｗｈａｔ　ｙｏｕ　ｔｈｉｎｋｉｎｇ？

Ｐｌｅａｓｅ　ｌｅｔ　ｕｓ　ｋｎｏｗ．

**Comment by nortti** [comment]
Ｔｈｅｒｅ　ｉｓ　ａ　ａｗｋｗａｒｄ　ｄｉｓｐａｒｉｔｙ　ｂｅｔｗｅｅｎ　ｔｈｅ　ｐｌａｃｅｈｏｌｄｅｒ　ｔｅｘｔ　ａｎｄ　ｔｈｅ　ｉｎｐｕｔ　ｔｅｘｔ　ｎｏｗ．　Ａ　ｎａｔｕｒａｌ　ｐｒｏｇｒｅｓｓｉｏｎ　ｉｓ　ｔｏ　ｍｏｖｅ　ｆｒｏｍ　ｇｒｅｙ　ｔｏ　ｗｈｉｔｅ　ｏｒ，　ｉｎ　ｔｈｉｓ　ｃａｓｅ，　ｆｒｏｍ　ａ　ｌｉｇｈｔｅｒ　ｂｌｕｅ　ｔｏ　ａ　ｄａｒｋｅｒ　ｂｌｕｅ．

Ａｎｙｗａｙ，　Ｉ　ｖｅｒｙ　ｍｕｃｈ　ｅｎｊｏｙ　ｂｅｉｎｇ　ａｂｌｅ　ｔｏ　ｒｅａｄ　ｔｈｅ　ｐｌａｃｅｈｏｌｄｅｒ　ｔｅｘｔ　ａｇａｉｎ，　ａｎｄ　Ｉ　ｃｏｎｓｉｄｅｒ　ｔｈｉｓ　ｔｉｃｋｅｔ　ｓｏｌｖｅｄ．　Ｙｏｕ　ｃａｎ　ｏｆ　ｃｏｕｒｓｅ　ｒｅ－ｏｐｅｎ　ｔｈｅ　ｔｉｃｋｅｔ　ｉｆ　ｙｏｕ　ｓｔｒｏｎｇｌｙ　ａｇｒｅｅ　ｔｈａｔ　ｔｈｅｒｅ　ｉｓ　ｓｔｉｌｌ　ａ　ｐｒｏｂｌｅｍ；　ｉｔ　ｉｓ　ｎｏｔ　ｍｙ　ｐｌａｃｅ　ｔｏ　ｓａｙ．

Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ　Ｌｅｘ，
Ｎｏｒｔｔｉ
